# Generated by Django 5.0.7 on 2024-09-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(editable=False, unique=True, upload_to='qr_codes/'),
        ),
    ]
